# Generated by Django 4.0.5 on 2022-07-03 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='lname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='reset',
            new_name='reset_password',
        ),
    ]
